import { expect, story } from "../../storybook/playwright/story"

story("rebinding updates the live composer and preserves native newline undo", async ({ mount }) => {
  const component = await mount("opencode-composer-flow--configurable-shortcuts")
  const input = component.getByRole("textbox", { name: "Prompt", exact: true })
  await component.getByRole("button", { name: "Enter for newline", exact: true }).click()
  await input.fill("hello")
  await input.press("Home")
  await input.press("ArrowRight")
  await input.press("Shift+ArrowRight")
  await input.press("Shift+ArrowRight")
  await input.press("Shift+ArrowRight")
  await input.press("Enter")
  await expect.poll(() => input.innerText()).toBe("h\no")
  await expect(component.getByRole("status")).toHaveText("Ready")
  await input.press("ControlOrMeta+z")
  await expect(input).toHaveText("hello")
  await input.press("Control+Enter")
  await expect(component.getByRole("status")).toHaveText("Submitted: hello")

  await component.getByRole("button", { name: "Disable shortcuts", exact: true }).click()
  await input.fill("unsent")
  await input.press("Enter")
  await input.press("Shift+Enter")
  await expect(input).toHaveText("unsent")
  await component.getByRole("button", { name: "Default shortcuts", exact: true }).click()
  await input.press("Enter")
  await expect(component.getByRole("status")).toHaveText("Submitted: unsent")
})
